name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    
env:
  IMAGE_TAG: czwr-mailing-profile    

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: make test
      
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  docker:
      name: build and publish Docker
      runs-on: ubuntu-latest
      needs: golangci
      steps:
        - uses: actions/checkout@v2
        - name: docker login
          env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
        - name: check image tag
          run: echo $IMAGE_TAG
        
        - name: build docker image 
          run: docker build --tag ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }} .
        
        - name: push image
          run: docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:latest

